import {
  auth,
  collaboratorAuth,
  collaboratorDb,
  collaboratorFunctions,
  firebaseApp,
  firebaseConfig,
  functions,
  isFirebaseConfigured,
  db,
} from "./client";
import {
  googleProvider,
  loginCollaboratorAnonymously,
  loginCollaboratorWithCustomToken,
  loginWithEmail,
  loginWithGoogle,
  logout,
  logoutCollaborator,
  onAuthStateChanged,
  registerWithEmail,
  sendResetEmail,
} from "./auth";
import {
  collectionOrderMap,
  createDocument,
  deleteDocument,
  listCollection,
  listWorkspaceCollection,
  normalizeFirestoreValue,
  setDocument,
  subscribeCollection,
  updateDocument,
} from "./firestore";
import {
  deleteStorageFile,
  downloadStorageFileDataUrl,
  getStorageDownloadUrl,
  uploadBase64,
  uploadFile,
  uploadPdfBytes,
} from "./storage";
import {
  backfillDeliverySignatures,
  callFunction,
  finalizeFaceDelivery,
  generateDeliveryReceipt,
  loadWorkspaceData,
  mintCollaboratorFaceToken,
  registerAuditLog,
  syncStockAlert,
  syncWorkspaceUnitContext,
} from "./functions";

export {
  auth,
  collaboratorAuth,
  firebaseApp,
  firebaseConfig,
  functions,
  isFirebaseConfigured,
  db,
  collaboratorDb,
  collaboratorFunctions,
  googleProvider,
  loginCollaboratorAnonymously,
  loginCollaboratorWithCustomToken,
  loginWithEmail,
  loginWithGoogle,
  logout,
  logoutCollaborator,
  onAuthStateChanged,
  registerWithEmail,
  sendResetEmail,
  collectionOrderMap,
  createDocument,
  deleteDocument,
  listCollection,
  listWorkspaceCollection,
  normalizeFirestoreValue,
  setDocument,
  subscribeCollection,
  updateDocument,
  deleteStorageFile,
  downloadStorageFileDataUrl,
  getStorageDownloadUrl,
  uploadBase64,
  uploadFile,
  uploadPdfBytes,
  callFunction,
  finalizeFaceDelivery,
  generateDeliveryReceipt,
  loadWorkspaceData,
  backfillDeliverySignatures,
  mintCollaboratorFaceToken,
  registerAuditLog,
  syncStockAlert,
  syncWorkspaceUnitContext,
};

export const firebaseApi = {
  list: listCollection,
  listWorkspace: listWorkspaceCollection,
  create: createDocument,
  set: setDocument,
  update: updateDocument,
  remove: deleteDocument,
  uploadBase64,
  uploadPdfBytes,
  downloadStorageFileDataUrl,
  backfillDeliverySignatures,
  finalizeFaceDelivery,
  loadWorkspaceData,
  mintCollaboratorFaceToken,
  syncWorkspaceUnitContext,
};
